site:
  title: Yoshihide Asciidoc Note
  url: https://github.com/YoshihideShirai/asciidoc-note
  start_page: software::index.adoc
  keys:
    google_analytics: 'G-V38Y5TJ2SC'
content:
  sources:
  - url: https://github.com/YoshihideShirai/asciidoc-note.git
    branches: HEAD
    start_paths: docs/*
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
  - asciidoctor-kroki
  - asciidoctor-emoji
antora:
  extensions:
  - require: '@antora/lunr-extension'
    languages: [en,ja]
ui:
  bundle:
    url: ./ui-bundle/
    snapshot: true
