site:
  title: Yoshihide Asciidoc Note
  url: https://github.com/YoshihideShirai/asciidoc-note
  start_page: math::index.adoc
content:
  sources:
  - url: https://github.com/YoshihideShirai/asciidoc-note
    branches: master
    edit_url: true
    start_paths: docs/*
asciidoc:
  attributes:
    experimental: ''
    idprefix: ''
    idseparator: '-'
    page-pagination: ''
  extensions:
  - asciidoctor-kroki
ui:
  bundle:
    url: https://gitlab.com/antora/antora-ui-default/-/jobs/artifacts/HEAD/raw/build/ui-bundle.zip?job=bundle-stable
    snapshot: true
